const Data = {
  productItems: [
    {
      id: 1,
      discount: 50,
      cover: "./images/flash/flash-1.png",
      name: "Women's Faux-Fur-Trim Hooded Maxi Puffer Coat",
      price: 100,
    },
    {
      id: 2,
      discount: 40,
      cover: "./images/flash/flash-2.png",
      name: "Women's Wool Blend Zip-Front Coat",
      price: 20,
    },
    {
      id: 3,
      discount: 40,
      cover: "./images/flash/flash-3.png",
      name: "Women's Plus Size Hooded Puffer Coat, Created for Macy's",
      price: 200,
    },
    {
      id: 4,
      discount: 40,
      cover: "./images/flash/flash-4.png",
      name: "Women's Hooded Fleece Drawstring Cardigan",
      price: 50,
    },
    {
      id: 5,
      discount: 50,
      cover: "./images/flash/flash-5.png",
      name: "Women's Faux-Leather Faux-Fur-Trim Trench Coat",
      price: 100,
    },
    {
      id: 6,
      discount: 50,
      cover: "./images/flash/shops-6.png",
      name: "Juniors' V-Neck Satin Gown, Created for Macy's",
      price: 100,
    },
    {
      id: 7,
      cover: "./images/flash/shops-1.png",
      name: "Women's 3-Stripe Tricot Track Jacket, XS-4X",
      price: "180",
      discount: "25",
    },
    {
      id: 8,
      cover: "./images/flash/shops-2.png",
      name: "Women's Cashmere Blend Belted Wrap Coat",
      price: "120",
      discount: "10",
    },
    {
      id: 9,
      cover: "./images/flash/shops-3.png",
      name: "Women's Hooded Packable Bomber Puffer Coat",
      price: "20",
      discount: "50 ",
    },
    {
      id: 10,
      cover: "./images/flash/shops-4.png",
      name: "Women's Faux-Wrap Maxi Dress, Created for Macy's",
      price: "999",
      discount: "10 ",
    },
    {
      id: 11,
      cover: "./images/flash/shops-5.png",
      name: "Women's Long-Sleeve Faux-Wrap Midi Dress",
      price: "80",
      discount: "20 ",
    },
    {
      id: 12,
      cover: "./images/flash/shops-7.png",
      name: "Women's 100% Cashmere Turtleneck Midi Dress, Regular & Petite, Created for Macy's",
      price: "400",
      discount: "20 ",
    },
    {
      id: 13,
      cover: "./images/flash/shops-8.png",
      name: "Women's Printed Long-Sleeve Family Matching Dress, Created for Macy's",
      price: "60",
      discount: "5 ",
    },
    {
      id: 14,
      cover: "./images/flash/shops-9.png",
      name: "Women's Essentials Embroidered Hooded Fleece Sweatshirt",
      price: "120",
      discount: "10",
    },
    {
      id: 15,
      cover: "./images/flash/shops-10.png",
      name: "Women's Raglan-Sleeve Mock-Neck Sweatshirt",
      price: "5",
      discount: "2",
    },
  ],
}
export default Data
